server:
  port: 8087
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

jpa:
  hibernate:
    ddl-auto: update #create update none
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    open-in-view: false
    show-sql: true

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/securityJwt
    username: sa
    password: 1234




